function constraint = f_GRF_2DSS(in1)
%F_GRF_2DSS
%    CONSTRAINT = F_GRF_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:18

F2 = in1(:,2);
constraint = F2;
