function constraint = f_qResetMap_2DSS(in1)
%F_QRESETMAP_2DSS
%    CONSTRAINT = F_QRESETMAP_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:10

q0p_1 = in1(:,8);
q0p_2 = in1(:,9);
q0p_3 = in1(:,10);
q0p_4 = in1(:,11);
q0p_5 = in1(:,12);
q0p_6 = in1(:,13);
q0p_7 = in1(:,14);
qN_2 = in1(:,2);
qN_3 = in1(:,3);
qN_4 = in1(:,4);
qN_5 = in1(:,5);
qN_6 = in1(:,6);
qN_7 = in1(:,7);
constraint = [q0p_1-sin(qN_3+qN_6).*(1.0./2.0)-sin(qN_3+qN_7).*(1.0./2.0);q0p_2-qN_2;q0p_3-qN_3;q0p_6-qN_4;q0p_7-qN_5;q0p_4-qN_6;q0p_5-qN_7];
