function constraint = f_steplength_2DSS(in1)
%F_STEPLENGTH_2DSS
%    CONSTRAINT = F_STEPLENGTH_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:18

q1L = in1(:,6);
q2L = in1(:,7);
qT = in1(:,3);
yH = in1(:,1);
constraint = yH-sin(q1L+qT).*(1.0./2.0)-sin(q2L+qT).*(1.0./2.0);
