function constraint = f_timeCont_2DSS(in1)
%F_TIMECONT_2DSS
%    CONSTRAINT = F_TIMECONT_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:16

T1 = in1(:,1);
T2 = in1(:,2);
constraint = T1-T2;
