function cost = f_torquePerSteplengthCost_2DSS(in1)
%F_TORQUEPERSTEPLENGTHCOST_2DSS
%    COST = F_TORQUEPERSTEPLENGTHCOST_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:19

q1L = in1(:,6);
q2L = in1(:,7);
qT = in1(:,3);
u1 = in1(:,8);
u2 = in1(:,9);
u3 = in1(:,10);
u4 = in1(:,11);
yH = in1(:,1);
t2 = abs(u1);
t3 = abs(u2);
t4 = abs(u3);
t5 = abs(u4);
cost = sqrt(t2.^2+t3.^2+t4.^2+t5.^2)./abs(-yH+sin(q1L+qT).*(1.0./2.0)+sin(q2L+qT).*(1.0./2.0));
