function constraint = f_torso_2DSS(in1)
%F_TORSO_2DSS
%    CONSTRAINT = F_TORSO_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:20

qT = in1(:,3);
constraint = qT;
