function cost = f_torqueCost_2DSS(in1)
%F_TORQUECOST_2DSS
%    COST = F_TORQUECOST_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:19

u1 = in1(:,1);
u2 = in1(:,2);
u3 = in1(:,3);
u4 = in1(:,4);
t2 = abs(u1);
t3 = abs(u2);
t4 = abs(u3);
t5 = abs(u4);
cost = sqrt(t2.^2+t3.^2+t4.^2+t5.^2);
