function J_constraint = J_GRF_2DSS(in1)
%J_GRF_2DSS
%    J_CONSTRAINT = J_GRF_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:18

J_constraint = [0.0,1.0];
