function J_constraint = J_holonomicAcc_2DSS(in1)
%J_HOLONOMICACC_2DSS
%    J_CONSTRAINT = J_HOLONOMICACC_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:08

ddq3 = in1(:,17);
ddq4 = in1(:,18);
ddq5 = in1(:,19);
dq1R = in1(:,11);
dq2R = in1(:,12);
dqT = in1(:,10);
q1R = in1(:,4);
q2R = in1(:,5);
qT = in1(:,3);
t2 = q1R+qT;
t3 = cos(t2);
t4 = q2R+qT;
t5 = cos(t4);
t6 = sin(t2);
t7 = sin(t4);
t8 = dq1R.*t3.*(1.0./2.0);
t9 = dq2R.*t5.*(1.0./2.0);
t10 = ddq4.*t6.*(1.0./2.0);
t11 = dqT.*t3.*(1.0./2.0);
t12 = t8+t11;
t13 = dq1R.*t12;
t14 = ddq5.*t7.*(1.0./2.0);
t15 = dqT.*t5.*(1.0./2.0);
t16 = t9+t15;
t17 = dq2R.*t16;
t18 = t6.*(1.0./2.0);
t19 = t7.*(1.0./2.0);
t20 = t18+t19;
t21 = dq1R.*t6;
t22 = dq2R.*t7;
t23 = t3.*(1.0./2.0);
t24 = t5.*(1.0./2.0);
t25 = t23+t24;
t26 = dq1R.*t6.*(1.0./2.0);
t27 = dq2R.*t7.*(1.0./2.0);
t28 = dqT.*t6.*(1.0./2.0);
t29 = t26+t28;
t30 = dq1R.*t29;
t31 = dqT.*t7.*(1.0./2.0);
t32 = t27+t31;
t33 = dq2R.*t32;
J_constraint = reshape([0.0,0.0,0.0,0.0,t10+t13+t14+t17+ddq3.*t20+dqT.*(t8+t9+dqT.*t25),t30+t33-ddq4.*t3.*(1.0./2.0)-ddq5.*t5.*(1.0./2.0)-ddq3.*t25+dqT.*(t26+t27+dqT.*t20),t10+t13+ddq3.*t6.*(1.0./2.0)+dqT.*t12,t30-ddq3.*t3.*(1.0./2.0)-ddq4.*t3.*(1.0./2.0)+dqT.*t29,t14+t17+ddq3.*t7.*(1.0./2.0)+dqT.*t16,t33-ddq3.*t5.*(1.0./2.0)-ddq5.*t5.*(1.0./2.0)+dqT.*t32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t21+t22+dqT.*t20.*2.0,-dq1R.*t3-dq2R.*t5-dqT.*t25.*2.0,t21+dqT.*t6,-dq1R.*t3-dqT.*t3,t22+dqT.*t7,-dq2R.*t5-dqT.*t5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,-t23-t24,-t18-t19,-t23,-t18,-t24,-t19,0.0,0.0,0.0,0.0],[2,21]);
