function J_constraint = J_pCont_2DSS(in1)
%J_PCONT_2DSS
%    J_CONSTRAINT = J_PCONT_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:16

J_constraint = reshape([1.0,0.0,0.0,1.0,-1.0,0.0,0.0,-1.0],[2,4]);
