function J_constraint = J_timeCont_2DSS(in1)
%J_TIMECONT_2DSS
%    J_CONSTRAINT = J_TIMECONT_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:16

J_constraint = [1.0,-1.0];
