function J_cost = J_torquePerSteplengthCost_2DSS(in1)
%J_TORQUEPERSTEPLENGTHCOST_2DSS
%    J_COST = J_TORQUEPERSTEPLENGTHCOST_2DSS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 01:06:19

q1L = in1(:,6);
q2L = in1(:,7);
qT = in1(:,3);
u1 = in1(:,8);
u2 = in1(:,9);
u3 = in1(:,10);
u4 = in1(:,11);
yH = in1(:,1);
t2 = q1L+qT;
t3 = sin(t2);
t4 = t3.*(1.0./2.0);
t5 = q2L+qT;
t6 = sin(t5);
t7 = t6.*(1.0./2.0);
t8 = t4+t7-yH;
t9 = abs(u1);
t10 = abs(u2);
t11 = abs(u3);
t12 = abs(u4);
t13 = abs(t8);
t14 = 1.0./t13.^2;
t15 = sign(t8);
t16 = t9.^2;
t17 = t10.^2;
t18 = t11.^2;
t19 = t12.^2;
t20 = t16+t17+t18+t19;
t21 = sqrt(t20);
t22 = cos(t2);
t23 = cos(t5);
t24 = 1.0./t13;
t25 = 1.0./sqrt(t20);
J_cost = [t14.*t15.*t21,0.0,-t14.*t15.*t21.*(t22.*(1.0./2.0)+t23.*(1.0./2.0)),0.0,0.0,t14.*t15.*t21.*t22.*(-1.0./2.0),t14.*t15.*t21.*t23.*(-1.0./2.0),t9.*t24.*t25.*sign(u1),t10.*t24.*t25.*sign(u2),t11.*t24.*t25.*sign(u3),t12.*t24.*t25.*sign(u4)];
